services:
    _defaults:
        public: false

    maurit_sms.prototype.provider.sms_ru:
        class: Maurit\Bundle\SmsBundle\Provider\SmsRuProvider

    maurit_sms.prototype.provider.sms_aero:
        class: Maurit\Bundle\SmsBundle\Provider\SmsAeroProvider

    maurit_sms.prototype.provider.sms_discount:
        class: Maurit\Bundle\SmsBundle\Provider\SmsDiscountProvider

    maurit_sms.prototype.provider.sms_center:
        class: Maurit\Bundle\SmsBundle\Provider\SmsCenterProvider

    maurit_sms.prototype.provider.message_bird:
        class: Maurit\Bundle\SmsBundle\Provider\MessageBirdProvider

    maurit_sms.provider.manager:
        class: Maurit\Bundle\SmsBundle\Service\ProviderManager

    Maurit\Bundle\SmsBundle\Service\ProviderManager: '@maurit_sms.provider.manager'

    maurit_sms.command.test_delivery:
        class: Maurit\Bundle\SmsBundle\Command\TestDeliveryCommand
        arguments: [ '@maurit_sms.provider.manager' ]
        tags:
            - { name: 'console.command' }
